import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { FormTemplate, AadhaarData } from '../types';

export const generateFormPDF = async (
  formTemplate: FormTemplate,
  formData: Record<string, string>,
  aadhaarData: AadhaarData
): Promise<void> => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  
  // Header
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Government of India', pageWidth / 2, 20, { align: 'center' });
  
  pdf.setFontSize(14);
  pdf.text(formTemplate.name, pageWidth / 2, 30, { align: 'center' });
  
  // Add a line
  pdf.setLineWidth(0.5);
  pdf.line(20, 35, pageWidth - 20, 35);
  
  // Form fields
  let yPosition = 50;
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  
  formTemplate.fields.forEach((field) => {
    const value = formData[field.id] || '';
    
    if (yPosition > pageHeight - 30) {
      pdf.addPage();
      yPosition = 20;
    }
    
    // Field label
    pdf.setFont('helvetica', 'bold');
    pdf.text(`${field.label}:`, 20, yPosition);
    
    // Field value
    pdf.setFont('helvetica', 'normal');
    pdf.text(value, 20, yPosition + 8);
    
    yPosition += 20;
  });
  
  // Footer
  pdf.setFontSize(10);
  pdf.text(`Generated on: ${new Date().toLocaleString()}`, 20, pageHeight - 20);
  pdf.text('Generated by Sahayika - Voice Form Assistant', 20, pageHeight - 10);
  
  // Save the PDF
  pdf.save(`${formTemplate.name.replace(/\s+/g, '_')}.pdf`);
};